services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    restart: always

    healthcheck:
      test: redis-cli ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
    networks:
      - redis-network

networks:
  redis-network:
    external: true
