apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: cloudflare-dns-creds
  namespace: traefik

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: cloudflare-dns-creds
    creationPolicy: Owner

  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare-dns-api-creds/api-token
    - secretKey: api-email
      remoteRef:
        key: cloudflare-dns-api-creds/api-email
