apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: rmq-creds
  namespace: infra

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: rmq-creds
    creationPolicy: Owner

  data:
    - secretKey: user
      remoteRef:
        key: rmq-creds/user
    - secretKey: password
      remoteRef:
        key: rmq-creds/password
