apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: onepassword

spec:
  provider:
    onepasswordSDK:
      vault: homelab_k8s_secrets

      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
          namespace: external-secrets